FROM postgres:12.5

ARG DEBIAN_FRONTEND=noninteractive

# Remove broken PostgreSQL repository
RUN rm -f /etc/apt/sources.list.d/pgdg.list

# Add official PostgreSQL repository
RUN echo "deb http://apt.postgresql.org/pub/repos/apt/ buster-pgdg main" > /etc/apt/sources.list.d/pgdg.list && \
    wget --quiet -O - https://www.postgresql.org/media/keys/ACCC4CF8.asc | apt-key add -

# Install dependencies and clean up APT cache
RUN apt-get update && apt-get install -y \
    ca-certificates \
    sudo \
    wget \
    curl \
    git \
    nano \
    libpq-dev \
    postgresql-server-dev-12 \
    build-essential \
    make \
    && rm -rf /var/lib/apt/lists/*

# Set password for 'postgres' user
RUN echo "postgres:postgres" | chpasswd && \
    usermod -aG sudo postgres

# Install pg_hint_plan
WORKDIR /root
RUN git clone --depth 1 --branch REL12_1_3_7 https://github.com/ossc-db/pg_hint_plan.git && \
    cd pg_hint_plan && \
    make PG_CONFIG=/usr/lib/postgresql/12/bin/pg_config && \
    make PG_CONFIG=/usr/lib/postgresql/12/bin/pg_config install && \
    cd .. && rm -rf pg_hint_plan

# Reset working directory
WORKDIR /