FROM nvidia/cuda:11.8.0-devel-ubuntu22.04

# Expose port
EXPOSE 5432

# Set environment variable to avoid interactive prompts
ENV DEBIAN_FRONTEND=noninteractive

# Install core system packages
RUN apt-get update && apt-get install -y \
    python3-dev \
    python3-pip \
    python-is-python3 \
    sudo \
    curl \
    git \
    vim \
    wget \
    unzip \
    pkg-config \
    build-essential \
    libssl-dev \
    make \
    cmake \
    gcc \
    gdb \
    clang \
    flex \
    bison \
    libreadline-dev \
    zlib1g-dev \
    libicu-dev \
    libclang-dev \
    llvm-dev \
    libcurl4-openssl-dev \
    libwebsockets-dev \
    libcjson-dev \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

# Set environment variables for Conda
ENV CONDA_DIR /opt/conda
ENV PATH $CONDA_DIR/bin:$PATH

# Install Miniconda (latest)
RUN wget --quiet https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh -O /tmp/miniconda.sh && \
    bash /tmp/miniconda.sh -b -p $CONDA_DIR && \
    rm /tmp/miniconda.sh && \
    conda clean -afy

# Default command — container stays alive
CMD ["tail", "-f", "/dev/null"]
